
spring.data.mongodb.uri=mongodb+srv://admin:Lumara2026@cluster0.zkmdmpc.mongodb.net/lumaraFit?retryWrites=true&w=majority
spring.data.mongodb.database=lumaraFit

# CONFIGURACIÓN DEL SERVIDOR
server.port=8080

# SEGURIDAD (Para que Postman no te bloquee)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration