# Nueva forma recomendada (sin el .data en el medio para la conexión principal)
spring.mongodb.uri=mongodb+srv://admin:Lumara2026@cluster0.zkmdmpc.mongodb.net/lumaraFit?retryWrites=true&w=majority

# Nombre de la base de datos
spring.mongodb.database=lumaraFit

# CONFIGURACIÓN DEL SERVIDOR
server.port=8080